namespace MS.Internal.Interop.DWrite
{
    /// <summary>
    /// Typographic feature of text supplied by the font.
    /// </summary>
    /// <remarks>
    /// Use DWRITE_MAKE_FONT_FEATURE_TAG() to create a custom one.
    /// <remarks>
    internal enum DWRITE_FONT_FEATURE_TAG
    {
        DWRITE_FONT_FEATURE_TAG_ALTERNATIVE_FRACTIONS               = (byte)'c' << 24 | (byte)'r' << 16 | (byte)'f' << 8 | (byte)'a',
        DWRITE_FONT_FEATURE_TAG_PETITE_CAPITALS_FROM_CAPITALS       = (byte)'c' << 24 | (byte)'p' << 16 | (byte)'2' << 8 | (byte)'c',
        DWRITE_FONT_FEATURE_TAG_SMALL_CAPITALS_FROM_CAPITALS        = (byte)'c' << 24 | (byte)'s' << 16 | (byte)'2' << 8 | (byte)'c',
        DWRITE_FONT_FEATURE_TAG_CONTEXTUAL_ALTERNATES               = (byte)'t' << 24 | (byte)'l' << 16 | (byte)'a' << 8 | (byte)'c',
        DWRITE_FONT_FEATURE_TAG_CASE_SENSITIVE_FORMS                = (byte)'e' << 24 | (byte)'s' << 16 | (byte)'a' << 8 | (byte)'c',
        DWRITE_FONT_FEATURE_TAG_GLYPH_COMPOSITION_DECOMPOSITION     = (byte)'p' << 24 | (byte)'m' << 16 | (byte)'c' << 8 | (byte)'c',
        DWRITE_FONT_FEATURE_TAG_CONTEXTUAL_LIGATURES                = (byte)'g' << 24 | (byte)'i' << 16 | (byte)'l' << 8 | (byte)'c',
        DWRITE_FONT_FEATURE_TAG_CAPITAL_SPACING                     = (byte)'p' << 24 | (byte)'s' << 16 | (byte)'p' << 8 | (byte)'c',
        DWRITE_FONT_FEATURE_TAG_CONTEXTUAL_SWASH                    = (byte)'h' << 24 | (byte)'w' << 16 | (byte)'s' << 8 | (byte)'c',
        DWRITE_FONT_FEATURE_TAG_CURSIVE_POSITIONING                 = (byte)'s' << 24 | (byte)'r' << 16 | (byte)'u' << 8 | (byte)'c',
        DWRITE_FONT_FEATURE_TAG_DEFAULT                             = (byte)'t' << 24 | (byte)'l' << 16 | (byte)'f' << 8 | (byte)'d',
        DWRITE_FONT_FEATURE_TAG_DISCRETIONARY_LIGATURES             = (byte)'g' << 24 | (byte)'i' << 16 | (byte)'l' << 8 | (byte)'d',
        DWRITE_FONT_FEATURE_TAG_EXPERT_FORMS                        = (byte)'t' << 24 | (byte)'p' << 16 | (byte)'x' << 8 | (byte)'e',
        DWRITE_FONT_FEATURE_TAG_FRACTIONS                           = (byte)'c' << 24 | (byte)'a' << 16 | (byte)'r' << 8 | (byte)'f',
        DWRITE_FONT_FEATURE_TAG_FULL_WIDTH                          = (byte)'d' << 24 | (byte)'i' << 16 | (byte)'w' << 8 | (byte)'f',
        DWRITE_FONT_FEATURE_TAG_HALF_FORMS                          = (byte)'f' << 24 | (byte)'l' << 16 | (byte)'a' << 8 | (byte)'h',
        DWRITE_FONT_FEATURE_TAG_HALANT_FORMS                        = (byte)'n' << 24 | (byte)'l' << 16 | (byte)'a' << 8 | (byte)'h',
        DWRITE_FONT_FEATURE_TAG_ALTERNATE_HALF_WIDTH                = (byte)'t' << 24 | (byte)'l' << 16 | (byte)'a' << 8 | (byte)'h',
        DWRITE_FONT_FEATURE_TAG_HISTORICAL_FORMS                    = (byte)'t' << 24 | (byte)'s' << 16 | (byte)'i' << 8 | (byte)'h',
        DWRITE_FONT_FEATURE_TAG_HORIZONTAL_KANA_ALTERNATES          = (byte)'a' << 24 | (byte)'n' << 16 | (byte)'k' << 8 | (byte)'h',
        DWRITE_FONT_FEATURE_TAG_HISTORICAL_LIGATURES                = (byte)'g' << 24 | (byte)'i' << 16 | (byte)'l' << 8 | (byte)'h',
        DWRITE_FONT_FEATURE_TAG_HALF_WIDTH                          = (byte)'d' << 24 | (byte)'i' << 16 | (byte)'w' << 8 | (byte)'h',
        DWRITE_FONT_FEATURE_TAG_HOJO_KANJI_FORMS                    = (byte)'o' << 24 | (byte)'j' << 16 | (byte)'o' << 8 | (byte)'h',
        DWRITE_FONT_FEATURE_TAG_JIS04_FORMS                         = (byte)'4' << 24 | (byte)'0' << 16 | (byte)'p' << 8 | (byte)'j',
        DWRITE_FONT_FEATURE_TAG_JIS78_FORMS                         = (byte)'8' << 24 | (byte)'7' << 16 | (byte)'p' << 8 | (byte)'j',
        DWRITE_FONT_FEATURE_TAG_JIS83_FORMS                         = (byte)'3' << 24 | (byte)'8' << 16 | (byte)'p' << 8 | (byte)'j',
        DWRITE_FONT_FEATURE_TAG_JIS90_FORMS                         = (byte)'0' << 24 | (byte)'9' << 16 | (byte)'p' << 8 | (byte)'j',
        DWRITE_FONT_FEATURE_TAG_KERNING                             = (byte)'n' << 24 | (byte)'r' << 16 | (byte)'e' << 8 | (byte)'k',
        DWRITE_FONT_FEATURE_TAG_STANDARD_LIGATURES                  = (byte)'a' << 24 | (byte)'g' << 16 | (byte)'i' << 8 | (byte)'l',
        DWRITE_FONT_FEATURE_TAG_LINING_FIGURES                      = (byte)'m' << 24 | (byte)'u' << 16 | (byte)'n' << 8 | (byte)'l',
        DWRITE_FONT_FEATURE_TAG_LOCALIZED_FORMS                     = (byte)'l' << 24 | (byte)'c' << 16 | (byte)'o' << 8 | (byte)'l',
        DWRITE_FONT_FEATURE_TAG_MARK_POSITIONING                    = (byte)'k' << 24 | (byte)'r' << 16 | (byte)'a' << 8 | (byte)'m',
        DWRITE_FONT_FEATURE_TAG_MATHEMATICAL_GREEK                  = (byte)'k' << 24 | (byte)'r' << 16 | (byte)'g' << 8 | (byte)'m',
        DWRITE_FONT_FEATURE_TAG_MARK_TO_MARK_POSITIONING            = (byte)'k' << 24 | (byte)'m' << 16 | (byte)'k' << 8 | (byte)'m',
        DWRITE_FONT_FEATURE_TAG_ALTERNATE_ANNOTATION_FORMS          = (byte)'t' << 24 | (byte)'l' << 16 | (byte)'a' << 8 | (byte)'n',
        DWRITE_FONT_FEATURE_TAG_NLC_KANJI_FORMS                     = (byte)'k' << 24 | (byte)'c' << 16 | (byte)'l' << 8 | (byte)'n',
        DWRITE_FONT_FEATURE_TAG_OLD_STYLE_FIGURES                   = (byte)'m' << 24 | (byte)'u' << 16 | (byte)'n' << 8 | (byte)'o',
        DWRITE_FONT_FEATURE_TAG_ORDINALS                            = (byte)'n' << 24 | (byte)'d' << 16 | (byte)'r' << 8 | (byte)'o',
        DWRITE_FONT_FEATURE_TAG_PROPORTIONAL_ALTERNATE_WIDTH        = (byte)'t' << 24 | (byte)'l' << 16 | (byte)'a' << 8 | (byte)'p',
        DWRITE_FONT_FEATURE_TAG_PETITE_CAPITALS                     = (byte)'p' << 24 | (byte)'a' << 16 | (byte)'c' << 8 | (byte)'p',
        DWRITE_FONT_FEATURE_TAG_PROPORTIONAL_FIGURES                = (byte)'m' << 24 | (byte)'u' << 16 | (byte)'n' << 8 | (byte)'p',
        DWRITE_FONT_FEATURE_TAG_PROPORTIONAL_WIDTHS                 = (byte)'d' << 24 | (byte)'i' << 16 | (byte)'w' << 8 | (byte)'p',
        DWRITE_FONT_FEATURE_TAG_QUARTER_WIDTHS                      = (byte)'d' << 24 | (byte)'i' << 16 | (byte)'w' << 8 | (byte)'q',
        DWRITE_FONT_FEATURE_TAG_REQUIRED_LIGATURES                  = (byte)'g' << 24 | (byte)'i' << 16 | (byte)'l' << 8 | (byte)'r',
        DWRITE_FONT_FEATURE_TAG_RUBY_NOTATION_FORMS                 = (byte)'y' << 24 | (byte)'b' << 16 | (byte)'u' << 8 | (byte)'r',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_ALTERNATES                = (byte)'t' << 24 | (byte)'l' << 16 | (byte)'a' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_SCIENTIFIC_INFERIORS                = (byte)'f' << 24 | (byte)'n' << 16 | (byte)'i' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_SMALL_CAPITALS                      = (byte)'p' << 24 | (byte)'c' << 16 | (byte)'m' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_SIMPLIFIED_FORMS                    = (byte)'l' << 24 | (byte)'p' << 16 | (byte)'m' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_1                     = (byte)'1' << 24 | (byte)'0' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_2                     = (byte)'2' << 24 | (byte)'0' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_3                     = (byte)'3' << 24 | (byte)'0' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_4                     = (byte)'4' << 24 | (byte)'0' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_5                     = (byte)'5' << 24 | (byte)'0' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_6                     = (byte)'6' << 24 | (byte)'0' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_7                     = (byte)'7' << 24 | (byte)'0' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_8                     = (byte)'8' << 24 | (byte)'0' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_9                     = (byte)'9' << 24 | (byte)'0' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_10                    = (byte)'0' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_11                    = (byte)'1' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_12                    = (byte)'2' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_13                    = (byte)'3' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_14                    = (byte)'4' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_15                    = (byte)'5' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_16                    = (byte)'6' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_17                    = (byte)'7' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_18                    = (byte)'8' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_19                    = (byte)'9' << 24 | (byte)'1' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_20                    = (byte)'0' << 24 | (byte)'2' << 16 | (byte)'s' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_SUBSCRIPT                           = (byte)'s' << 24 | (byte)'b' << 16 | (byte)'u' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_SUPERSCRIPT                         = (byte)'s' << 24 | (byte)'p' << 16 | (byte)'u' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_SWASH                               = (byte)'h' << 24 | (byte)'s' << 16 | (byte)'w' << 8 | (byte)'s',
        DWRITE_FONT_FEATURE_TAG_TITLING                             = (byte)'l' << 24 | (byte)'t' << 16 | (byte)'i' << 8 | (byte)'t',
        DWRITE_FONT_FEATURE_TAG_TRADITIONAL_NAME_FORMS              = (byte)'m' << 24 | (byte)'a' << 16 | (byte)'n' << 8 | (byte)'t',
        DWRITE_FONT_FEATURE_TAG_TABULAR_FIGURES                     = (byte)'m' << 24 | (byte)'u' << 16 | (byte)'n' << 8 | (byte)'t',
        DWRITE_FONT_FEATURE_TAG_TRADITIONAL_FORMS                   = (byte)'d' << 24 | (byte)'a' << 16 | (byte)'r' << 8 | (byte)'t',
        DWRITE_FONT_FEATURE_TAG_THIRD_WIDTHS                        = (byte)'d' << 24 | (byte)'i' << 16 | (byte)'w' << 8 | (byte)'t',
        DWRITE_FONT_FEATURE_TAG_UNICASE                             = (byte)'c' << 24 | (byte)'i' << 16 | (byte)'n' << 8 | (byte)'u',
        DWRITE_FONT_FEATURE_TAG_VERTICAL_WRITING                    = (byte)'t' << 24 | (byte)'r' << 16 | (byte)'e' << 8 | (byte)'v',
        DWRITE_FONT_FEATURE_TAG_VERTICAL_ALTERNATES_AND_ROTATION    = (byte)'2' << 24 | (byte)'t' << 16 | (byte)'r' << 8 | (byte)'v',
        DWRITE_FONT_FEATURE_TAG_SLASHED_ZERO                        = (byte)'o' << 24 | (byte)'r' << 16 | (byte)'e' << 8 | (byte)'z',
    }
}
